# Generated by Django 5.2.4 on 2025-07-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('mapel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalMengajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru.guru')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(max_length=10)),
                ('nama_kelas', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='StatusModel',
        ),
        migrations.AddField(
            model_name='jadwalmengajar',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru.kelas'),
        ),
    ]
